"""
Django settings for my_first_site project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
import re

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qgcn(ah46k8e3f)ft$oxoxrsl2%d2j6$b4zayh=g(#23i8uj7m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'dafe-46-46-103-193.ngrok-free.app']

# Application definition

INSTALLED_APPS = [
    'graphene_django',
    'daphne',
    'psycopg2',
    'corsheaders',
    'django_elasticsearch_dsl',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog.apps.CatalogConfig',
    'test_db_sharding',
    'graphql_test',
    'test_elasticSearch',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', 
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'my_first_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_first_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db_elasticsearch_test.sqlite3',
    # },
    'default': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': BASE_DIR / 'db.sqlite3',
    },
    'db2': {
       'ENGINE': 'django.db.backends.postgresql',
       'NAME': 'db2',
       'USER': 'postgres',
       'PASSWORD': 'q1346798520',
       'HOST': '4.tcp.eu.ngrok.io',
       'PORT': '16795',
    },
    'db_qgraphql_test': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': BASE_DIR / 'db_graphql_test.sqlite3',
    },
    'db_elasticsearch_test': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': BASE_DIR / 'db_elasticsearch_test.sqlite3',
    }
}

GRAPHENE = {  
    'SCHEMA': 'my_first_site.schema.schema'
}

AUTH_USER_MODEL = 'catalog.CustomUser'

#AUTHENTICATION_BACKENDS = ['catalog.backends.CustomModelBackend']
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

#STATIC_URL = '/static/'
STATIC_URL = '/catalog/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'catalog', 'static'),  # Директория статических файлов приложения app1
    os.path.join(BASE_DIR, 'graphql_test', 'static'),  # Директория статических файлов приложения app2
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/catalog/'

# Путь хранения картинок
MEDIA_ROOT = os.path.join(BASE_DIR, 'catalog/')


ASGI_APPLICATION = "my_first_site.asgi.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

DATE_INPUT_FORMATS = ['%d-%m-%Y']

CSRF_TRUSTED_ORIGINS = ['https://dafe-46-46-103-193.ngrok-free.app','https://*.127.0.0.1','ws://d827-46-46-103-193.ngrok-free.app',]

#CSRF_COOKIE_SECURE = False
#CSRF_COOKIE_SAMESITE = None

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = (
    'http://localhost:8000',
    'https://dafe-46-46-103-193.ngrok-free.app',  # замените xxxxx на вашу subdomain в Ngrok
)

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CORS_ALLOW_HEADERS = '*'

ELASTICSEARCH_DSL={
    'default': {
        'hosts': 'http://127.0.0.1:9200',
        'http_auth': ('elastic', 'ySB6LGiZb6Juwxxp7GQj')
    }
}