# Generated by Django 4.2.4 on 2023-08-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='GraphQLArticle',
        ),
    ]
