# Generated by Django 4.1.5 on 2023-04-20 17:34

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.user_profile_photo_directory_path),
        ),
    ]
